### ISSUE TITLE
The PVS1.LOF.genes is incorrectly named

### ISSUE THREAD

**Issue by ftucos** [WGLab/CancerVar#2]
The python script is looking for a file named PVS1.LOF.genes (original name in InterVar) but it's actual name in the repo is LOF.genes.exac_me_cancers

**Comment by quanliustc** [comment]
what's your cancervar'sconfig.ini, are you using config.ini from InterVar? It seems your config.ini not the right one.
try to re-download and un-pack it to another folder.
