### ISSUE TITLE
Missing files in cancervardb

### ISSUE THREAD

**Issue by ftucos** [WGLab/CancerVar#4]
The _cancer_pathway.list_ file is missing in cancervardb.
I downloaded it from the vicdb https://github.com/HGLab/VIC/tree/master/vicdb 

Also, the _cancer_census.genes_ file should be renamed _cancer_genes.list_

**Comment by quanliustc** [comment]
You are mixture using config.ini with intervar and vic, 
In cancervar, it is "cancers_genes.list_kegg.txt"
Please re-download whole packages, and store it in another folder.

**Comment by ftucos** [comment]
Thank you for answering.
My config.ini was ok; I was trying to launch the script by manually passing the arguments and looking at the _CancerVar.py_ script I was expecting different file names (the same as VIC):
`if options.database_cancervar != None:
        paras['database_cancervar']=options.database_cancervar
        paras['lof_genes'] = paras['database_cancervar']+'/PVS1.LOF.genes'
        paras['mim2gene'] =paras['database_cancervar']+'/mim2gene.txt'
        paras['mim_pheno'] = paras['database_cancervar']+'/mim_pheno.txt'
        paras['mim_orpha'] = paras['database_cancervar']+'/mim_orpha.txt'
        paras['orpha'] = paras['database_cancervar']+'/orpha.txt'
        paras['knowngenecanonical'] = paras['database_cancervar']+'/knownGeneCanonical.txt'
        paras['exclude_snps'] = paras['database_cancervar']+'/ext.variants'
        paras['cancer_pathway'] =paras['database_cancervar']+'/cancer_pathway.list'
        paras['cancers_genes'] =paras['database_cancervar']+'/cancers_genes.list'
        paras['cancers_types']=paras['database_cancervar']+'/cancervar.cancer.types'`
Now I launched it setting up the _config.ini_ and it's working!
Thank you for the clarification.

**Comment by quanliustc** [comment]
don't suggest to do that, also VIC datasets and coding  were from eraly alpha version of cancervar.
Now cancervar have re-built the datasets and files.
