### ISSUE TITLE
Difference between CancerVar and InterVar?

### ISSUE THREAD

**Issue by lincj1994** [WGLab/CancerVar#9]
Hi. Is there any difference between cancervar and intervar? Is intervar only suitable for germline variants annotation? Or is cancervar of more clinical values?

**Comment by quanliustc** [comment]
CancerVar is specific for cancer somatic mutations, while InterVar is for germline mutations. The criteria and evidence are totally different.

**Comment by lincj1994** [comment]
Thanks. I've read many papers using intervar for somatic variant annotations. 
BTW, for germline variants, guidelines have been described to classify variants in biological classes as well as tier-based clinical interpretation classes. But for somatic variants however, only guidelines for the clinical interpretation have been extensively described. So can Intervar output be also used for somatic variants as a reference and supplement?

**Comment by lincj1994** [comment]
Hi. 
`5. Some updated datasets(cosmic and icgc) for Annovar: https://cancervar.wglab.org/databases/ (download and gunzip, put in the Annovar db folder)`
I cannot open the url.

**Comment by quanliustc** [comment]
list was disabled in the server, now should be ok. But most files are already in Annovar database.

**Comment by lincj1994** [comment]
Hi. CancerVar cannot keep the tumor sample barcode in the otherinfo column of the output. The same problem as previous version of InterVar.

**Comment by quanliustc** [comment]
This was from the column header name issue from new version of Annovar, now fixed.

**Comment by lincj1994** [comment]
So should I re-download the entire CancerVar or just the CancerVar.py？

**Comment by quanliustc** [comment]
you can just download the new version of CancerVar.py

**Comment by lincj1994** [comment]
Thank you. 
Another two questions:
1. What the input should be like if I want to perform command-line CancerVar for CNA data. I dont find the example data in this repository.
2. In your CancerVar article in bioRxiv, you stated that CancerVar contains all the above 12 evidence, among which 10 of them are automatically generated and the other two, including variant allele fraction and potential germline, require user input for manual adjustment. I dont know which argument of command-line cancervar is used for manual adjustmeng.
